// Mock data for courses
export const courses = [
  {
    id: 1,
    title: "Advanced JavaScript Patterns",
    description: "Learn modern JavaScript patterns and advanced concepts to level up your development skills.",
    category: "JavaScript",
    thumbnail: "https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?auto=format&q=80&w=400&h=225&fit=crop",
    totalModules: 8,
    level: "advanced",
    instructor: "Sarah Williams",
    duration: "6 weeks",
    rating: 4.8,
    enrolledStudents: 1245,
    topics: [
      "Closures and Scope",
      "Prototypal Inheritance",
      "Functional Programming",
      "Asynchronous Patterns",
      "ES6+ Features",
      "Design Patterns",
      "Performance Optimization",
      "Testing Strategies"
    ]
  },
  {
    id: 2,
    title: "React Performance Optimization",
    description: "Master techniques to build faster, more efficient React applications with advanced optimization strategies.",
    category: "React",
    thumbnail: "https://images.unsplash.com/photo-1633356122102-3fe601e05bd2?auto=format&q=80&w=400&h=225&fit=crop",
    totalModules: 10,
    level: "intermediate",
    instructor: "Michael Chen",
    duration: "8 weeks",
    rating: 4.9,
    enrolledStudents: 987,
    topics: [
      "Component Lifecycle",
      "React Hooks Optimization",
      "Memoization Techniques",
      "Code Splitting",
      "Bundle Size Reduction",
      "Server-Side Rendering",
      "State Management",
      "Virtualization",
      "Lazy Loading",
      "Performance Profiling"
    ]
  },
  {
    id: 3,
    title: "Data Analysis with Python",
    description: "Learn how to analyze and visualize data effectively with Python, pandas, and matplotlib.",
    category: "Python",
    thumbnail: "https://images.unsplash.com/photo-1602992708529-c9fdb12905c9?auto=format&q=80&w=400&h=225&fit=crop",
    totalModules: 7,
    level: "beginner",
    instructor: "David Kumar",
    duration: "5 weeks",
    rating: 4.7,
    enrolledStudents: 1532,
    topics: [
      "Python Basics",
      "Data Structures",
      "Pandas Fundamentals",
      "Data Cleaning",
      "Statistical Analysis",
      "Data Visualization",
      "Machine Learning Intro"
    ]
  },
  {
    id: 4,
    title: "Full Stack Web Development",
    description: "Build complete web applications from front to back using modern technologies and best practices.",
    category: "Web Development",
    thumbnail: "https://images.unsplash.com/photo-1593720213428-28a5b9e94613?auto=format&q=80&w=400&h=225&fit=crop",
    totalModules: 12,
    level: "intermediate",
    instructor: "Sophia Rodriguez",
    duration: "10 weeks",
    rating: 4.6,
    enrolledStudents: 2145,
    topics: [
      "HTML/CSS Fundamentals",
      "JavaScript Essentials",
      "React Frontend",
      "Node.js Backend",
      "RESTful APIs",
      "Database Design",
      "Authentication",
      "Deployment",
      "Testing",
      "Security",
      "Performance",
      "Project Architecture"
    ]
  },
  {
    id: 5,
    title: "Mobile App Development with Flutter",
    description: "Create beautiful, natively compiled applications for mobile, web, and desktop from a single codebase.",
    category: "Mobile Development",
    thumbnail: "https://images.unsplash.com/photo-1551650975-87deedd944c3?auto=format&q=80&w=400&h=225&fit=crop",
    totalModules: 9,
    level: "intermediate",
    instructor: "Alex Johnson",
    duration: "7 weeks",
    rating: 4.8,
    enrolledStudents: 876,
    topics: [
      "Dart Programming",
      "Flutter Basics",
      "UI Components",
      "State Management",
      "Navigation",
      "API Integration",
      "Local Storage",
      "Firebase Integration",
      "Publishing Apps"
    ]
  },
  {
    id: 6,
    title: "DevOps Engineering",
    description: "Master the tools and practices for continuous integration, delivery, and deployment in modern software development.",
    category: "DevOps",
    thumbnail: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?auto=format&q=80&w=400&h=225&fit=crop",
    totalModules: 8,
    level: "advanced",
    instructor: "James Wilson",
    duration: "8 weeks",
    rating: 4.7,
    enrolledStudents: 654,
    topics: [
      "CI/CD Pipelines",
      "Docker Containerization",
      "Kubernetes Orchestration",
      "Infrastructure as Code",
      "Cloud Services",
      "Monitoring and Logging",
      "Security Practices",
      "Scaling Strategies"
    ]
  }
];